base_url = "https://ganarchy.github.io/"

[repo_list_srcs]
"https://ganarchy.autistic.space/index.toml" = { active=true }

[projects.385e734a52e13949a7a5c71827f6de920dbfea43]
"https://soniex2.autistic.space/git-repos/ganarchy.git".HEAD = { active=true }

[projects.125baefaade696119262cd7ae5127c4265a59edc]
"https://github.com/arclanguage/anarki".HEAD = { active=true }


[projects.e1ee4fc7c093b7c983de16f314789154e9ef96df]
"https://github.com/SoniEx2/ClassiCube-Client".HEAD = { active=true }

[projects.c0b4a8a326a320ac33c5d9d6bac2f7ea7eb703ce]
"https://ipfs.io/ipfs/QmUN3hj69aGMeGyTQuG3GZdTHkaCaf2fAfWGeNSyyNjiVC".HEAD = { active=false }

[projects.d6a17fdd92b690e2584d743c153b45ba4d684d30]
"https://github.com/SoniEx2/cw2-hexchat".HEAD = { active=true }

[projects.886b8bd893b8f0186d508d8ae295a6974829bdc7]
"https://soniex2.autistic.space/git-repos/htmlgdump.git".HEAD = { active=true }

[projects.dd26b5f3aa8108c3026080c734878e541c4cd05c]
"https://soniex2.autistic.space/git-repos/uwumode.git".HEAD = { active=true }

[projects.1cf233f31ba84dba2b7cbcde6c160b0fdf4141ac]
"https://github.com/diracdeltas/tweets".HEAD = { active=true }
"https://github.com/sanasol/tweets".HEAD = { active=true }
"https://github.com/jmdelahanty/tweets".HEAD = { active=true }
"https://github.com/JerukPurut404/tweets".HEAD = { active=true }
"https://github.com/alexandredelaitre/tweets".HEAD = { active=true }
"https://github.com/schnow265/tweets".HEAD = { active=true }
"https://github.com/GorgorRaleria/tweets".HEAD = { active=true }
"https://github.com/staffanm/tweets".HEAD = { active=true }
"https://github.com/shubhodeep9/tweets".HEAD = { active=true }
"https://github.com/cao-minh-duc/tweets".HEAD = { active=true }
"https://github.com/crimson-med/tweets".HEAD = { active=true }
"https://github.com/Dfmaaa/tweets".HEAD = { active=true }
"https://github.com/jmona789/tweets".HEAD = { active=true }
"https://github.com/JohnTrapp/tweets".HEAD = { active=true }
"https://github.com/aphiwadChhoeun/tweets".HEAD = { active=true }
"https://github.com/blackfloret/tweets".HEAD = { active=true }
"https://github.com/1ipod/tweets".HEAD = { active=true }
"https://github.com/hbcbh1999/tweets".HEAD = { active=true }
"https://github.com/plasticboy/tweets".HEAD = { active=true }
"https://github.com/fejimene/tweets".HEAD = { active=true }
"https://github.com/waytoarcher/tweets".HEAD = { active=true }
"https://github.com/re-gend/tweets".HEAD = { active=true }
"https://github.com/samisbakedham/tweets".HEAD = { active=true }
"https://github.com/hatsuseno/tweets".HEAD = { active=true }
"https://github.com/akuinu/tweets".HEAD = { active=true }
"https://github.com/iotku/tweets".HEAD = { active=true }
"https://github.com/me-mariosteve/tweets".HEAD = { active=true }
"https://github.com/AgeOfMarcus/tweets".HEAD = { active=true }
"https://github.com/Baugrems/tweets".HEAD = { active=true }
"https://github.com/alexthill/tweets".HEAD = { active=true }
"https://github.com/ukra174/tweets".HEAD = { active=true }
"https://github.com/gigatexal/tweets".HEAD = { active=true }
"https://github.com/carrag/tweets".HEAD = { active=true }
"https://github.com/lorenzo-dev1/tweets".HEAD = { active=true }
"https://github.com/dlmanning/tweets".HEAD = { active=true }
"https://github.com/encukou/tweets".HEAD = { active=true }
"https://github.com/Pdzly/tweets".HEAD = { active=true }
"https://github.com/techopsking/tweets".HEAD = { active=true }
"https://github.com/yk-sgr/tweets".HEAD = { active=true }
"https://github.com/pjeanjean/tweets".HEAD = { active=true }
"https://github.com/SebRollen/tweets".HEAD = { active=true }
"https://github.com/JKirchartz/tweets".HEAD = { active=true }
"https://github.com/Kangie/tweets".HEAD = { active=true }
"https://github.com/janmysiak/tweets".HEAD = { active=true }
"https://github.com/alexanderflink/tweets".HEAD = { active=true }
"https://github.com/openfnord/tweets".HEAD = { active=true }
"https://github.com/heyLu/tweets".HEAD = { active=true }
"https://github.com/nilskj/tweets".HEAD = { active=true }
"https://github.com/lgastler/tweets".HEAD = { active=true }
"https://github.com/aquilax/tweets".HEAD = { active=true }
"https://github.com/BenediktBroich/tweets".HEAD = { active=true }
"https://github.com/claydugo/tweets".HEAD = { active=true }
"https://github.com/varikvalefor/tweets".HEAD = { active=true }
"https://github.com/bhatti/tweets".HEAD = { active=true }
"https://github.com/YuheiNakasaka/tweets".HEAD = { active=true }
"https://github.com/yurafuca/tweets".HEAD = { active=true }
"https://github.com/hoangphuctv/tweets".HEAD = { active=true }
"https://github.com/dai/tweets".HEAD = { active=true }
"https://github.com/KonstantinWilleke/tweets".HEAD = { active=true }
"https://github.com/AndrewFeeney/tweets".HEAD = { active=true }
"https://github.com/Mrorlovsky/tweets".HEAD = { active=true }
"https://github.com/6arms1leg/tweets".HEAD = { active=true }
"https://github.com/Ranplax/tweets".HEAD = { active=true }
"https://github.com/jVincentl/tweets".HEAD = { active=true }
"https://github.com/robertwatts/tweets".HEAD = { active=true }
"https://github.com/guites/tweets".HEAD = { active=true }
"https://github.com/FedericoSchonborn/tweets".HEAD = { active=true }
"https://github.com/ahmedyounes/tweets".HEAD = { active=true }
"https://github.com/noncombatant/tweets".HEAD = { active=true }
"https://github.com/bbrewington/tweets".HEAD = { active=true }
"https://github.com/kgrimes2/tweets".HEAD = { active=true }
"https://github.com/jaandrle/tweets".HEAD = { active=true }
"https://github.com/ob6160/tweets".HEAD = { active=true }
"https://github.com/hackthehackerman/tweets".HEAD = { active=true }
"https://github.com/bxio/tweets".HEAD = { active=true }
"https://github.com/jchook/tweets".HEAD = { active=true }
"https://github.com/impetus1/jointhehype".HEAD = { active=true }
"https://github.com/TylerJaacks/tweets".HEAD = { active=true }
"https://github.com/waltforme/tweets".HEAD = { active=true }
"https://github.com/johnsusek/tweets".HEAD = { active=true }
"https://github.com/jawakarD/tweets".HEAD = { active=true }
"https://github.com/ka2n/tweets".HEAD = { active=true }
"https://github.com/will/tweets".HEAD = { active=true }
"https://github.com/davidsan/tweets".HEAD = { active=true }
"https://github.com/SuzukiRyuichiro/tweets".HEAD = { active=true }
"https://github.com/mcharo/tweets".HEAD = { active=true }
"https://github.com/ckmahoney/tweets".HEAD = { active=true }
"https://github.com/weeble/tweets".HEAD = { active=true }
"https://github.com/montoulieu/tweets".HEAD = { active=true }
"https://github.com/akky/tweets".HEAD = { active=true }
"https://github.com/usual4/tweets".HEAD = { active=true }
"https://github.com/ixns/tweets".HEAD = { active=true }
"https://github.com/Foxboron/tweets".HEAD = { active=true }
"https://github.com/Jaeyo/tweets".HEAD = { active=true }
"https://github.com/posix4e/tweets".HEAD = { active=true }
"https://github.com/gpummer/tweets".HEAD = { active=true }
"https://github.com/kr1sp1n/tweets".HEAD = { active=true }
"https://github.com/danielcherubini/tweets".HEAD = { active=true }
"https://github.com/TheLortex/tweets".HEAD = { active=true }
"https://github.com/TallerThanShort/tweets".HEAD = { active=true }
"https://github.com/cpunion/tweets".HEAD = { active=true }
"https://github.com/liquuid/tweets".HEAD = { active=true }
"https://github.com/xeloader/tweets".HEAD = { active=true }
"https://github.com/juev/tweets".HEAD = { active=true }
"https://github.com/WesSouza/tweets".HEAD = { active=true }
"https://github.com/smithographic/tweets".HEAD = { active=true }
"https://github.com/devdoshi/tweets".HEAD = { active=true }
"https://github.com/mayli/tweets".HEAD = { active=true }
"https://github.com/gautamswostik/tweets".HEAD = { active=true }
"https://github.com/mullikine/tweets".HEAD = { active=true }
"https://github.com/monophylos/tweets".HEAD = { active=true }
"https://github.com/vinthony/tweets".HEAD = { active=true }
"https://github.com/FatGrizzly/tweets".HEAD = { active=true }
"https://github.com/tcdowney/tweets".HEAD = { active=true }
"https://github.com/tekknolagi/tweets".HEAD = { active=true }
"https://github.com/houhoulis/tweets".HEAD = { active=true }
"https://github.com/searls/tweets".HEAD = { active=true }
"https://github.com/mikejurney/tweets".HEAD = { active=true }
"https://github.com/AlexDarigan/tweets".HEAD = { active=true }
"https://github.com/mabhub/tweets".HEAD = { active=true }
"https://github.com/miyagawa/tweets".HEAD = { active=true }
"https://github.com/horihiro/tweets".HEAD = { active=true }
"https://github.com/sneakers-the-rat/tweets".HEAD = { active=true }
"https://github.com/IreneKnapp/tweets".HEAD = { active=true }
"https://github.com/darius/tweets".HEAD = { active=true }
"https://github.com/evilalmus/tweets".HEAD = { active=true }
"https://github.com/girliemac/tweets".HEAD = { active=true }
"https://github.com/EverlastingBugstopper/tweets".HEAD = { active=true }
"https://github.com/fitsum/tweets".HEAD = { active=true }
"https://github.com/jenwich/tweets".HEAD = { active=true }
"https://github.com/fuglede/tweets".HEAD = { active=true }
"https://github.com/casually-blue/tweets".HEAD = { active=true }
"https://github.com/oberernst/tweets".HEAD = { active=true }
"https://github.com/nulltrope/tweets".HEAD = { active=true }
"https://github.com/honglu2875/tweets".HEAD = { active=true }
"https://github.com/adrianmejias/tweets".HEAD = { active=true }
"https://github.com/markcaudill/tweets".HEAD = { active=true }
"https://github.com/sgillies/tweets".HEAD = { active=true }
"https://github.com/isfu/tweets".HEAD = { active=true }
"https://github.com/milovincent/tweets".HEAD = { active=true }
"https://github.com/akherxn/tweets".HEAD = { active=true }
"https://github.com/Luminoth/tweets".HEAD = { active=true }
"https://github.com/jwupf/tweets".HEAD = { active=true }
"https://github.com/ahailes/tweets".HEAD = { active=true }
"https://github.com/TheBorinator/tweets".HEAD = { active=true }
"https://github.com/oblazy/tweets".HEAD = { active=true }
"https://github.com/benfulton/tweets".HEAD = { active=true }
"https://github.com/ahaltindis/tweets".HEAD = { active=true }
"https://github.com/Schoonology/tweets".HEAD = { active=true }
"https://github.com/est/gitweets".HEAD = { active=true }
"https://github.com/yevhenorlov/tweets".HEAD = { active=true }
"https://github.com/japonophile/tweets".HEAD = { active=true }
"https://github.com/doytsujin/tweets".HEAD = { active=true }
"https://github.com/bermannoah/tweets".HEAD = { active=true }
"https://github.com/DuqueDeTuring/tweets".HEAD = { active=true }
"https://github.com/jvns/tweets".HEAD = { active=true }
"https://github.com/sdaveas/tweets".HEAD = { active=true }
"https://github.com/donaldguy/tweets".HEAD = { active=true }
"https://github.com/teaguehannam/tweets".HEAD = { active=true }
"https://github.com/JonathanWThom/tweets".HEAD = { active=true }
"https://github.com/lynnpepin/tweets".HEAD = { active=true }
"https://github.com/bayareagamedevs/tweets".HEAD = { active=true }
"https://github.com/jsocol/tweets".HEAD = { active=true }
"https://github.com/mrcichon/tweets".HEAD = { active=true }
"https://github.com/pyrito/tweets".HEAD = { active=true }
"https://github.com/aneeshdurg/tweets".HEAD = { active=true }
"https://github.com/ttrreevvoorr/gitter".HEAD = { active=true }
"https://github.com/Ademsk1/tweets".HEAD = { active=true }
"https://github.com/super-cooper/tweets".HEAD = { active=true }
"https://github.com/gengel/tweets".HEAD = { active=true }
"https://github.com/jackfurr/tweets".HEAD = { active=true }
"https://github.com/hspak/tweets".HEAD = { active=true }
"https://github.com/jorjordandan/tweets".HEAD = { active=true }
"https://github.com/blueForestIcarus/tweets".HEAD = { active=true }
"https://github.com/jamesgmorgan/tweets".HEAD = { active=true }
"https://github.com/n3wjack/tweets".HEAD = { active=true }
"https://github.com/sep332/tweets".HEAD = { active=true }
"https://github.com/mrose17/tweets".HEAD = { active=true }
"https://github.com/DerekNonGeneric/yanspace".HEAD = { active=true }
"https://github.com/paraparata/tweets".HEAD = { active=true }
"https://github.com/gamb/tweets".HEAD = { active=true }
"https://github.com/neuschaefer/tweets".HEAD = { active=true }
"https://github.com/asafonov/tweets".HEAD = { active=true }
"https://github.com/datn/tweets".HEAD = { active=true }
"https://github.com/eth4io/tweets".HEAD = { active=true }
"https://github.com/numbertheory/bunny-tweets".HEAD = { active=true }
"https://github.com/stuartpb/tweets".HEAD = { active=true }
"https://github.com/vivshaw/tweets".HEAD = { active=true }
