base_url = "https://ganarchy.github.io/"

[repo_list_srcs]
"https://ganarchy.autistic.space/index.toml" = { active=true }

[projects.125baefaade696119262cd7ae5127c4265a59edc]
"https://github.com/arclanguage/anarki".HEAD = { active=true }

[projects.385e734a52e13949a7a5c71827f6de920dbfea43]
"https://soniex2.autistic.space/git-repos/ganarchy.git".HEAD = { active=true }

[projects.e1ee4fc7c093b7c983de16f314789154e9ef96df]
"https://github.com/SoniEx2/ClassiCube-Client".HEAD = { active=true }

[projects.c0b4a8a326a320ac33c5d9d6bac2f7ea7eb703ce]
"https://ipfs.io/ipfs/QmUN3hj69aGMeGyTQuG3GZdTHkaCaf2fAfWGeNSyyNjiVC".HEAD = { active=false }

[projects.d6a17fdd92b690e2584d743c153b45ba4d684d30]
"https://github.com/SoniEx2/cw2-hexchat".HEAD = { active=true }
